AWSTemplateFormatVersion: "2010-09-09"
Resources:
  myKey:
    Type: "AWS::KMS::Key"
    Properties:
      Description: "An example symmetric encryption KMS key"
      EnableKeyRotation: true
      PendingWindowInDays: 20
      KeyPolicy:
        Version: "2012-10-17"
        Id: "key-default-1"
        Statement:
          - Sid: "Enable IAM User Permissions"
            Effect: "Allow"
            Principal:
              AWS: '*'
            Action: "kms:*"
            Resource: "*"
            # Condition:
            #   StringEquals:
            #     "aws:PrincipalArn": "arn:aws:iam::111122223333:user/Alice"
  SampleBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref DOC-EXAMPLE-BUCKET
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 's3:GetObject'
            Effect: Allow
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref DOC-EXAMPLE-BUCKET
                - /*
            Principal: '*'
            Condition:
              StringLike:
                'aws:Referer':
                  - 'http://www.example.com/*'
                  - 'http://example.net/*'